apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlNekF4TWpreApNakkxTWpOYUZ3MDBNekF4TWpreE1qSTFNak5hTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFEdmVRblZzRXU1TnNBQ2xXVFhhQ1NCTW9LZkJkN3Nld080elZtZ3E4ajVlc3RHbDR0UApGNjIyS2UvRk5ibThFcW1HczVkSkJPbThtd0lsRjZGZVNTczRJK1VrWWQ4VUFLOE5kVS9WeHc0MDQzT0hGOTlCClZ4SkF4bjkyVnlpTlBBd0xEdzFKTkhmTWFWcDNLZmhRNHNrUVVHVFRrbHhlWDFEek5FeHpxZFRXdm1ZK0toOGcKZ0ltUHM2WnYrMmk3L1MvTmN0Z2pyVEcxcnNURnk2dUtiQUo5cWxtUW5oK3NibUNJOGdCVGhWVFlYNXpSWHZxLwphb01Ua2VuWVBERXlhUWRlZmdKR252UjhidmJibkVZbmZQc3dOcmNXM1lkQytxYlVqTFV4dTN6cTFOdzI3aXhHCm9OUGxjYnJDYlhlcUJUbzFFS3V1RnZ0V3VQSEZXNW9aays3bkFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlQ5Y0JjN2pKQ1JnblJqMzBCUwprajM5QncxT0tEQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFSN3lRKzl6Mytobm13dmdjUXAzVm5mVm8veFNYCmlvTEZjYTU0Y0lSKzNudGZxSmRkTWNQSkxWZSs0b1RtUHNDYTV1S0hFRENPbkFSeUtUL1pjcUlWa0NlUTg5ZWcKTzlwQ0VrUGpnSVpJUnlxVUdhZWg1YjlxRWJmWit0S1RhNVRaTEVENmg4dVlCV2JxWE81ajNjemdmSmZZZk5hdApFUEVabkg4ODBjd2grdW4zUVFnNUFQUGhveHVvelZlM2pLVXZDUGpRaDcyUjFjOVVYSUZoQ1UxaHpqYnpyVmZFCkd6UFpQU294dTI2eU9lVTZ0TS8wL0dmRFpCS085UUgrcXdkelFPK1FlcWpacGpLSEg0OUplTVl3QStERVBTNWkKTGpQRFJZNjZSMllmUHZDU2VRdHVmaWVuSjNGYlhmL1ltZmUxNndWUnV2VXBHRzIrQk5WVjZ5MlJYQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://490d01d7-1a2c-4600-8056-2abeea160cc5.k8s.ondigitalocean.com
  name: do-nyc3-k8s
contexts:
- context:
    cluster: do-nyc3-k8s
    user: do-nyc3-k8s-admin
  name: do-nyc3-k8s
current-context: do-nyc3-k8s
users:
- name: do-nyc3-k8s-admin
  user:
    token: dop_v1_dc4a77a3775dc879ad4171720d167b9dbb18f7e1e13732abfe113d5dd5b74144
